version: "3.3"
services:
  db:
    image: redis:7.0-rc2-bullseye
  reviewme:
    build: .
    image: reviewme:latest
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 6379
      TIMEOUT: 30
